// Code generated by protoc-gen-go.
// source: go-simple-apm.proto
// DO NOT EDIT!

/*
Package go_simple_apm is a generated protocol buffer package.

It is generated from these files:
	go-simple-apm.proto

It has these top-level messages:
	Result
	CpuStatus
*/
package go_simple_apm

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Result struct {
	Result bool `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Result) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type CpuStatus struct {
	Modelname string    `protobuf:"bytes,1,opt,name=modelname" json:"modelname,omitempty"`
	Cores     int32     `protobuf:"varint,2,opt,name=cores" json:"cores,omitempty"`
	Status    []float64 `protobuf:"fixed64,3,rep,packed,name=status" json:"status,omitempty"`
}

func (m *CpuStatus) Reset()                    { *m = CpuStatus{} }
func (m *CpuStatus) String() string            { return proto.CompactTextString(m) }
func (*CpuStatus) ProtoMessage()               {}
func (*CpuStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CpuStatus) GetModelname() string {
	if m != nil {
		return m.Modelname
	}
	return ""
}

func (m *CpuStatus) GetCores() int32 {
	if m != nil {
		return m.Cores
	}
	return 0
}

func (m *CpuStatus) GetStatus() []float64 {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*Result)(nil), "Result")
	proto.RegisterType((*CpuStatus)(nil), "CpuStatus")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for APM service

type APMClient interface {
	SendCpuStatus(ctx context.Context, in *CpuStatus, opts ...grpc.CallOption) (*Result, error)
}

type aPMClient struct {
	cc *grpc.ClientConn
}

func NewAPMClient(cc *grpc.ClientConn) APMClient {
	return &aPMClient{cc}
}

func (c *aPMClient) SendCpuStatus(ctx context.Context, in *CpuStatus, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/APM/SendCpuStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for APM service

type APMServer interface {
	SendCpuStatus(context.Context, *CpuStatus) (*Result, error)
}

func RegisterAPMServer(s *grpc.Server, srv APMServer) {
	s.RegisterService(&_APM_serviceDesc, srv)
}

func _APM_SendCpuStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CpuStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APMServer).SendCpuStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/APM/SendCpuStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APMServer).SendCpuStatus(ctx, req.(*CpuStatus))
	}
	return interceptor(ctx, in, info, handler)
}

var _APM_serviceDesc = grpc.ServiceDesc{
	ServiceName: "APM",
	HandlerType: (*APMServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendCpuStatus",
			Handler:    _APM_SendCpuStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "go-simple-apm.proto",
}

func init() { proto.RegisterFile("go-simple-apm.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 167 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0xcf, 0xd7, 0x2d,
	0xce, 0xcc, 0x2d, 0xc8, 0x49, 0xd5, 0x4d, 0x2c, 0xc8, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57,
	0x52, 0xe0, 0x62, 0x0b, 0x4a, 0x2d, 0x2e, 0xcd, 0x29, 0x11, 0x12, 0xe3, 0x62, 0x2b, 0x02, 0xb3,
	0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x82, 0xa0, 0x3c, 0xa5, 0x70, 0x2e, 0x4e, 0xe7, 0x82, 0xd2,
	0xe0, 0x92, 0xc4, 0x92, 0xd2, 0x62, 0x21, 0x19, 0x2e, 0xce, 0xdc, 0xfc, 0x94, 0xd4, 0x9c, 0xbc,
	0xc4, 0xdc, 0x54, 0xb0, 0x3a, 0xce, 0x20, 0x84, 0x80, 0x90, 0x08, 0x17, 0x6b, 0x72, 0x7e, 0x51,
	0x6a, 0xb1, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0x84, 0x03, 0x32, 0xb8, 0x18, 0xac, 0x5b,
	0x82, 0x59, 0x81, 0x59, 0x83, 0x31, 0x08, 0xca, 0x33, 0xd2, 0xe5, 0x62, 0x76, 0x0c, 0xf0, 0x15,
	0x52, 0xe3, 0xe2, 0x0d, 0x4e, 0xcd, 0x4b, 0x41, 0xd8, 0xc1, 0xa5, 0x07, 0x67, 0x4b, 0xb1, 0xeb,
	0x41, 0x5c, 0xa7, 0xc4, 0x90, 0xc4, 0x06, 0x76, 0xb0, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x92,
	0xaa, 0xbf, 0x3e, 0xc7, 0x00, 0x00, 0x00,
}
